### ISSUE TITLE
What would be the best way to anonymize specific attributes in a JSONB column

### ISSUE THREAD

**Issue by cmer** [evilmartians/evil-seed#12]
One of my models has a JSONB column with attributes a few levels deep. What is the preferred way to clean up some of these attributes?

**Comment by Envek** [comment]
You can use `customize` syntax (`anonymize` is a sugar for it basically).

E.g. following snippet will add suffix `-test` to values of `key` key in `data` column:
```ruby
EvilSeed.configure do |config|
  config.customize('User') do |attributes|
    attributes['data'].merge!('key' => attributes['data']['key] + '-test')
  end
end
```

**Comment by cmer** [comment]
This is awesome thank you!!!
